### ISSUE TITLE
disinfectPayload cast all my arrays into strings

### ISSUE THREAD

**Issue by ghost** [genediazjr/disinfect#4]
Hi,

I was testing this plugin to sanitize my payload. However is seems like any array contained in my payload is cast into a string.
Example payload :
`{
	"text1": "test a",
	"text2": "test b",
	"array": [
		{
			"text3": "test c",
			"text4": "test d"
		},
		{
			"text3": "test e",
			"text4": "test f"
		}
	]
}`

Result :
`{"text1":"test a","text2":"test b","array":"[object Object],[object Object]"}`

**Comment by genediazjr** [comment]
This is fixed on the recent pr. Thanks!
