### ISSUE TITLE
Disinfect giving "TypeError: Cannot assign to read only property '0' of string" during sanitation

### ISSUE THREAD

**Issue by TheInfinity007** [genediazjr/disinfect#8]
I am using hapi server and I want to use joi header validation( for content-type: 'application/json') in my PUT method.

The problem comes when the user sends a valid json in payload and sends 'content-type' header with value 'text/css' or 'text/javascript'.  On postAuth this payload as a stringified string goes to disinfect and it is throwing error. 

`TypeError: Cannot assign to read only property '0' of string`

Because of this the request in not reaching to the joi validation, which is present at the route level.

It can be one of the edge cases. Ideally the purpose of disinfect is the sanitation of the request data and should not throw error.

I am also attaching the request curl

`curl --location --request PUT 'http://localhost:3000/blogs/b1' \
--header 'Content-Type: text/css' \
--data-raw '{ "text1": "test a", "text2": "test b" }'`

`
    "error": {
        "code": "Internal Server Error",
        "message": "An internal server error occurred",
        "statusCode": 500,
        "trace": "TypeError: Cannot assign to read only property '0' of string '{ \"text1\": \"test a\", \"text2\": \"test b\" }'\n    at Object.internals.sanitize (/Users/infinity/Desktop/myAppService/node_modules/disinfect/lib/index.js:37:26)\n    at Object.internals.disinfect (/Users/infinity/Desktop/myAppService/node_modules/disinfect/lib/index.js:75:34)\n    at /Users/infinity/Desktop/myAppService/node_modules/disinfect/lib/index.js:137:45\n    at exports.Manager.execute (/Users/infinity/Desktop/myAppService/node_modules/@hapi/hapi/lib/toolkit.js:57:29)\n    at Request._invoke (/Users/infinity/Desktop/myAppService/node_modules/@hapi/hapi/lib/request.js:391:55)\n    at Request._lifecycle (/Users/infinity/Desktop/myAppService/node_modules/@hapi/hapi/lib/request.js:364:86)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Request._execute (/Users/infinity/Desktop/myAppService/node_modules/@hapi/hapi/lib/request.js:273:9)"
    }`

**Comment by TheInfinity007** [comment]
I have found the place from where it is giving error

https://github.com/genediazjr/disinfect/blob/master/lib/index.js#L37

Since the obj (on line 24 is of type string, and we are trying to reassign the characters using index which is not possible in javascript and will give `TypeError: Cannot assign to read only property '0' of string` error

**Comment by genediazjr** [comment]
published v2
